### ISSUE TITLE
Passing `-r /some/rpmlint/rc` causes `AttributeError`

### ISSUE THREAD

**Issue by mgerstner** [rpm-software-management/rpmlint#740]
This is about the opensuse branch variant. When passing `-r /some/rpmlint/rc` then an Exception occurs:

```
rpmlint -v my.rpm -r myrc
Traceback (most recent call last):
  File "/usr/bin/rpmlint", line 33, in <module>
    sys.exit(load_entry_point('rpmlint==2.1.0', 'console_scripts', 'rpmlint')())
  File "/usr/lib/python3.8/site-packages/rpmlint/cli.py", line 187, in lint
    lint = Lint(options)
  File "/usr/lib/python3.8/site-packages/rpmlint/lint.py", line 43, in __init__
    self._load_rpmlintrc()
  File "/usr/lib/python3.8/site-packages/rpmlint/lint.py", line 196, in _load_rpmlintrc
    self.config.load_rpmlintrc(rcfile)
  File "/usr/lib/python3.8/site-packages/rpmlint/config.py", line 160, in load_rpmlintrc
    rpmlintrc_lines = rpmlintrc_file.read_text().splitlines()
AttributeError: 'list' object has no attribute 'read_text'
```

The cause is this line where the parameter is turned into a `list`, introduced in commit 3ec4e4ea:

https://github.com/rpm-software-management/rpmlint/blob/opensuse/rpmlint/cli.py#L110

**Comment by marxin** [comment]
Fixed.
